CREATE TABLE IF NOT EXISTS orders ( 
   customerId INT PRIMARY KEY AUTO_INCREMENT, 
   customerName VARCHAR(20) NOT NULL, 
   orderDate DATE NOT NULL, 
   address VARCHAR(255) NOT NULL,
   total DOUBLE NOT NUll,
   PRIMARY KEY (customerId)
);

CREATE TABLE IF NOT EXISTS ORDERITEM ( 
 customerId INT PRIMARY KEY AUTO_INCREMENT, 
 productCode VARCHAR(20) NOT NULL, 
 productName VARCHAR(20) NOT NULL, 
 quantity INT NOT NULL 
);